[versions]
androidGradlePlugin = "8.12.3"
kotlin = "1.9.22"
activityCompose = "1.8.2"
composeBom = "2024.02.01"
coreKtx = "1.12.0"
appcompat = "1.6.1"
lifecycle = "2.7.0"
navigationCompose = "2.7.7"
firebaseBom = "32.7.4"
googleServices = "4.4.1"
moshi = "1.15.0"
retrofit = "2.9.0"
materialIcons = "1.6.6"
junit = "4.13.2"
androidxTestExtJunit = "1.1.5"
rendering = "1.17.1"
firebasePerf = "1.4.2" # ✅ BARU: Versi Plugin Performance
firebasePerfKtx = "20.5.2" # ✅ BARU: Versi Library (bisa ikut BOM sebenarnya, tapi define aja biar aman)

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx"}
firebase-perf = { module = "com.google.firebase:firebase-perf", version.ref = "firebasePerfKtx" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }

androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIcons" }

moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
rendering = { group = "com.google.ar.sceneform", name = "rendering", version.ref = "rendering" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }